### ISSUE TITLE
Feature: in SP, pause timer when the game is paused

### ISSUE THREAD

**Issue by rgoliveira** [oskros/MF_counter_releases#1]
First of all, thanks for this project! It's great!

So, as the title says, in single-player it'd be great if the timer stopped when we hit <kbd>ESC</kbd>. Not sure if it's possible at all with your current memory reader, but thought I'd open this issue.

If it's trivial, feel free to give me some direction and I could do it myself.

**Comment by oskros** [comment]
Might be possible, first you need to find a memory address that is True when the game is paused and false otherwise. That might be available somewhere in this list: https://github.com/planqi/slashdiablo-maphack/blob/master/BH/D2Ptrs.h
If not, some research to finding that address would be needed.

After that it's simply a matter of mapping it in the "map_ptrs" function found here for each patch version: 
https://github.com/oskros/MF_counter_releases/blob/master/memory_reader/reader.py#L180-L194

And finally, a function could be created to monitor this address and hook it up to the UI, which should probably be done in the functions "_update_lap_time" and "_update_session_time" here:
https://github.com/oskros/MF_counter_releases/blob/master/tabs/mf_timer.py#L69-L77

Not trivial, but possible if the memory address can be located. 

Also some case handling should be made to not make the application crash if you don't select to have automode on (since this would entail memory readying, and that is only allowed when using advanced automode)

**Comment by oskros** [comment]
Actually instead of changing "_update_lap_time" and "_update_session_time", it's probably easier to just invoke the "pause" function when the game is paused 👍 
https://github.com/oskros/MF_counter_releases/blob/master/tabs/mf_timer.py#L237-L268

**Comment by rgoliveira** [comment]
I might've found the memory location, but I don't have much time ATM to work on this, so it might take me a while to submit a proper PR...

If you're interested, I'm looking at address `D2Client.dll+FADA4`. It becomes `1` whenever I'm in the in-game menu, and `0` otherwise. I haven't tested it thoroughly, though, just grabbed it with Cheat Engine in a few minutes of experimenting.

PS: I'm running patch 1.13c.

**Comment by oskros** [comment]
Cool, it seems to work for me as well with this address.

I have found the addresses for patch 1.14b+c+d as well from another library, so just need to get the one for 1.13d then I will be happy to make the implementation

I am not familiar with cheat engine, so if you wouldn't mind helping out with getting the address for 1.13d then I will be happy to make the implementation

**Comment by oskros** [comment]
turned out the addresses I found for 1.14b+c+d didnt work. I have however added this feature in the latest commit, but wont release until I have accumulated some more features and also hopefully found addresses for the remaining patch versions

If you would like to help with finding addresses it would be appreciated, if you have time ofc.

closing the issue
