### ISSUE TITLE
Disable hotkeys if Diablo isn't the active window

### ISSUE THREAD

**Issue by rgoliveira** [oskros/MF_counter_releases#3]
It's common to leave the game open and do something else (Discord, search something, etc.). When out of the game, it's undesirable to trigger the hotkeys. As it happens, the hotkeys I use in the run counter clash with a few other apps' (and even Windows').

**Comment by oskros** [comment]
It would be easy to implement a feature that makes hotkeys not fire when Diablo is not in focus. However it would be more difficult to actually unbind and rebind them every time focus is changed from Diablo - this I don't have a good idea of how to do.

If I go with the first suggestion, the app would still overwrite hotkeys for other applications when out of focus, but pressing them would not have any effect. Is this solution acceptable for you? Otherwise I will think a bit more on what could be done.

**Comment by oskros** [comment]
Decided this wont be made. It will cause issues in other parts of the program. Sorry about that
